pull request #1
Sputnikccy/newYearResolution pull request #1
Opened 2022-11-02 18:39 UTC by Sputnikccy

test

2022-11-02 20:16 UTC, TristanThorburn requested changes

2022-11-02 20:16 UTC, TristanThorburn commented on src/DisplayAnnualReview.js
> +                    <img src={require("./assets/notebook.png")}  alt="notebook" className="notebook" />
The assets notebook says Imcomplete Facts About me this year, did you mean "Your/My iNcomplete year so far"?

2022-11-02 20:16 UTC, TristanThorburn commented on src/AnnualReviewForm.js
> +    const handleShowInput = (e) => {
Could possible change the display because the code calls it show and the display is for movie

2022-11-02 20:16 UTC, TristanThorburn commented on src/ResolutionForm.js.js
> +            console.log(savedResolutionData);
remove console logs

2022-11-02 20:16 UTC, TristanThorburn commented on src/ResolutionForm.js.js
> +            const errorDescription = 'glitch image'
For the screen readers I would maybe say no images match your resolution as glitch image is a bit confusing

2022-11-02 20:16 UTC, TristanThorburn commented on src/Book.js
> +    console.log(props)
Assignment outline suggests removing console logs and possibly pseudo code though yours was really helpful

2022-11-02 20:16 UTC, TristanThorburn commented on src/ResolutionForm.js.js
> +      console.log(newState)
remove console log

2022-11-02 20:16 UTC, TristanThorburn commented on src/App.css
> +  scroll-behavior: smooth;
I've never seen this before and I'm stealing it <3

2022-11-02 20:16 UTC, TristanThorburn commented on src/App.js
> +        <h2>Close eyes to old ends</h2>
For these h2s I would add your to say Open your heart to new beginnings

2022-11-02 20:16 UTC, TristanThorburn commented on src/App.css
> -@media (prefers-reduced-motion: no-preference) {
I like how you were thinking about this, I dont remember seeing it in our Juno courses and Chris and I have been looking into accessibility resources

2022-11-03 01:14 UTC, Sputnikccy commented on src/DisplayAnnualReview.js
> +                    <img src={require("./assets/notebook.png")}  alt="notebook" className="notebook" />
Hahah it means the questions in the form are just part of "me" around the year, not enough to summarize a person. I'll think about a better expression :)

2022-11-03 03:57 UTC, merged